In [1]:


import numpy as np
n=np.array([1,2,3,4,5],dtype='int32')
print(n.dtype)
print (n.shape)
print(n.ndim)
print(n.nbytes)
print(n.itemsize)
print(n.size*n.itemsize)



int32
(5,)
1
20
4
20


In [35]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
print(a[1,2])
print(a[:,3])
print(a[1,:])
print(a[1,2:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
8
[4 9]
[ 6  7  8  9 10]
[ 8  9 10]


In [50]:
a=np.array([[[1,2,3],[4,5,6]],[[6,5,4],[3,2,1]]])
print(a)
print(a.ndim,a.shape)
print(a[:,1,1])

[[[1 2 3]
  [4 5 6]]

 [[6 5 4]
  [3 2 1]]]
3 (2, 2, 3)
[5 2]


In [43]:
np.zeros((5,3,3))


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [45]:
np.ones((2,2),datatype="int32")

array([[1., 1.],
       [1., 1.]])

In [59]:
np.full((3,3),22,dtype="float")




array([[22., 22., 22.],
       [22., 22., 22.],
       [22., 22., 22.]])

In [61]:
print(a.nbytes)
print(a.size)
print(a.size*a.itemsize)
print(np.full_like(a,5))
print(np.full(a.shape,1))

48
12
48
[[[5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]]]
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [275]:
print(np.random.rand(4,3))
print(np.random.randint(1,10,size=(4,2)))
print(np.random.random_sample(a.shape))
np.random.randint(-2,5,size=(2,2))

[[0.27028068 0.29954365 0.33383098]
 [0.81769483 0.20747269 0.47548767]
 [0.66240682 0.78107772 0.48003149]
 [0.68962094 0.77740959 0.92016649]]
[[9 9]
 [7 9]
 [9 1]
 [2 3]]
[0.22896047 0.43637667 0.09133032 0.2976752  0.62430184]


array([[2, 3],
       [3, 0]])

In [72]:
print(np.identity(5))




[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [78]:
# axis =1 horizontally(inside column)
# axis=0 vertical (whole row first)
array=np.array([[1,2,3],[4,5,6]])
r1=np.repeat(array,2,axis=0)
r2=np.repeat(array,2,axis=1)
print(r1)
print(r2)

[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]]
[[1 1 2 2 3 3]
 [4 4 5 5 6 6]]


In [85]:
a=np.ones((5,5))
print(a)
z=np.zeros((3,3))
z[1,1]=9
a[1:4,1:4]=z
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [108]:
a=np.array([1,2,3,4,5])
print(a)
print(a+2)
print(a-2)
print(a/a)
print(a*a)
b=np.array([1,0,1,0,1])
print(a+b)
print(np.add(a,b))
x=np.array([[1,2,3],[22,31,1]])
y=np.array([[1,2],[55,9],[14,31]])
# print(x*y)throwing error
print(np.matmul(x,y))
print(a**2)
print(np.cos(a))

[1 2 3 4 5]
[3 4 5 6 7]
[-1  0  1  2  3]
[1. 1. 1. 1. 1.]
[ 1  4  9 16 25]
[2 2 4 4 6]
[2 2 4 4 6]
[[ 153  113]
 [1741  354]]
[ 1  4  9 16 25]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [116]:
n=np.random.randint(1,20, size=(3,3))
print(n)
print(np.linalg.det(n))

[[ 1 15 10]
 [ 3 19  9]
 [ 5 13  1]]
-27.999999999999986


In [124]:
stats=np.array([[1,2,3],[4,5,6]])
print(np.min(stats,axis=0))
print(np.min(stats,axis=1))
print(np.max(stats,axis=0))
print(np.max(stats,axis=1))
print(np.sum(stats,axis=0))
print(np.sum(stats,axis=1))
print(stats.reshape(6))
print(stats.reshape(3,2))






[1 2 3]
[1 4]
[4 5 6]
[3 6]
[5 7 9]
[ 6 15]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [135]:
v1=np.ones((2,3))
v2=np.zeros((5,3))
print(np.vstack((v1,v2)))
v1=np.ones((2,5))
v2=np.zeros((2,3))
print(np.hstack((v1,v2)))



[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0.]]


In [276]:
array=np.random.randint(1000,size=(3,18))
print(array)
print(array[array>50])
print(np.any(array>50,axis=0))
print(np.any(array>50,axis=1))
print(np.all(array>50,axis=0))
print(np.all(array>50,axis=1))
print(array[(array>50) & (array<100)])
print(array[~((array>50) & (array<100))])


[[717 823  13 924  57 954 197 995 567 584 333 127 390  75 444 140 839  13]
 [  9 200 787 858 436 413 718 240 389 280  92 169  70  39 316 781 350 345]
 [669 538 433 299 111 871 776 497 463 495 747 156 184 432 606 750 650 676]]
[717 823 924  57 954 197 995 567 584 333 127 390  75 444 140 839 200 787
 858 436 413 718 240 389 280  92 169  70 316 781 350 345 669 538 433 299
 111 871 776 497 463 495 747 156 184 432 606 750 650 676]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True]
[ True  True  True]
[False  True False  True  True  True  True  True  True  True  True  True
  True False  True  True  True False]
[False False  True]
[57 75 92 70]
[717 823  13 924 954 197 995 567 584 333 127 390 444 140 839  13   9 200
 787 858 436 413 718 240 389 280 169  39 316 781 350 345 669 538 433 299
 111 871 776 497 463 495 747 156 184 432 606 750 650 676]
